title: Gmod-lua-weaponsets
description: Garry's mod addon. It adds to game weapon and ammunition sets (kits).
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
